vim.pack.add({
	{ src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", name = "nvim-treesitter" },
	{ src = "https://github.com/neovim/nvim-lspconfig", name = "nvim-lspconfig" },
	{ src = "https://github.com/DivinerSun/lsp_lines.nvim", name = "lsp_lines" },
	{ src = "https://github.com/mason-org/mason.nvim", name = "mason.nvim" },
	{ src = "https://github.com/mason-org/mason-lspconfig.nvim", name = "mason-lspconfig.nvim" },
	{ src = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim", name = "mason-tool-installer.nvim" },
	{ src = "https://github.com/saghen/blink.compat", name = "blink.compat" },
	{ src = "https://github.com/saghen/blink.lib", name = "blink.lib" },
	{ src = "https://github.com/saghen/blink.cmp", name = "blink.cmp" },
	{ src = "https://github.com/hrsh7th/nvim-cmp", name = "nvim-cmp" },
	{ src = "https://github.com/Exafunction/codeium.nvim", name = "codeium.nvim" },
	{ src = "https://github.com/Exafunction/windsurf.nvim", name = "windsurf.nvim" },
	{ src = "https://github.com/mikavilpas/blink-ripgrep.nvim", name = "blink-ripgrep.nvim" },
	{ src = "https://github.com/moyiz/blink-emoji.nvim", name = "blink-emoji.nvim" },
	{ src = "https://github.com/MahanRahmati/blink-nerdfont.nvim", name = "blink-nerdfont.nvim" },
	{ src = "https://github.com/stevearc/conform.nvim", name = "conform.nvim" },
	{ src = "https://github.com/mrcjkb/rustaceanvim", name = "rustaceanvim" },
	{ src = "https://github.com/mfussenegger/nvim-dap", name = "nvim-dap" },
	{ src = "https://github.com/rcarriga/nvim-dap-ui", name = "nvim-dap-ui" },
	{ src = "https://github.com/nvim-neotest/nvim-nio", name = "nvim-nio" },
	{ src = "https://github.com/nvim-neotest/neotest", name = "neotest" },
	{ src = "https://github.com/lewis6991/gitsigns.nvim", name = "gitsigns.nvim" },
	{ src = "https://github.com/echasnovski/mini.comment", name = "mini.comment" },
	{ src = "https://github.com/echasnovski/mini.pairs", name = "mini.pairs" },
	{ src = "https://github.com/echasnovski/mini.surround", name = "mini.surround" },
	{ src = "https://github.com/ibhagwan/fzf-lua", name = "fzf-lua" },
	{ src = "https://github.com/folke/which-key.nvim", name = "which-key.nvim" },
	{ src = "https://github.com/nvim-lualine/lualine.nvim", name = "lualine.nvim" },
	{ src = "https://github.com/nvim-lua/plenary.nvim", name = "plenary.nvim" },
	{ src = "https://github.com/MunifTanjim/nui.nvim", name = "nui.nvim" },
	{ src = "https://github.com/nvim-tree/nvim-web-devicons", name = "nvim-web-devicons" },
	{ src = "https://github.com/nvim-neo-tree/neo-tree.nvim", name = "neo-tree.nvim" },
	{ src = "https://github.com/saifulapm/neotree-file-nesting-config", name = "neotree-file-nesting-config" },
	{ src = "https://github.com/folke/todo-comments.nvim", name = "todo-comments.nvim" },
	{ src = "https://github.com/mg979/vim-visual-multi", name = "vim-visual-multi" },
	{ src = "https://github.com/DivinerSun/showkeys", name = "showkeys" },
	{ src = "https://github.com/akinsho/toggleterm.nvim", name = "toggleterm.nvim" },
	{ src = "https://github.com/rcarriga/nvim-notify", name = "nvim-notify" },
	{ src = "https://github.com/folke/noice.nvim", name = "noice.nvim" },
	{ src = "https://github.com/b0o/incline.nvim", name = "incline.nvim" },
	{ src = "https://github.com/SmiteshP/nvim-navic", name = "nvim-navic" },
	{ src = "https://github.com/folke/snacks.nvim", name = "snacks.nvim" },
}, {
	confirm = false,
	load = true,
})
